### ISSUE TITLE
Typings - filename

### ISSUE THREAD

**Issue by alexbainbridge** [Kinvey/angular2-sdk#1]
Hello @ThomasConner 

Great work on the Angular 2 library. Works in Angular 2 JS, but has a few challenges when used in Angular 2 Typescript

The typings file, currently in develop branch, is called typings.d.ts

If you look at the module resolution documentation
https://www.typescriptlang.org/docs/handbook/module-resolution.html

either
A] This filename is good, but then you need to mention it in the package.json as the typings value

or
B] call the filename index.d.ts as an easy solution 

Thanks!
Alex

**Comment by ThomasConner** [comment]
@alexbainbridge Thanks for the help. Since #2 is related I am going to close this issue and track the typings process there.
