### ISSUE TITLE
Kinvey / Ionic 2 / Typescript / Rollup-Webpack - variety of issues

### ISSUE THREAD

**Issue by alexbainbridge** [Kinvey/angular2-sdk#2]
Hello @ThomasConner 

I know you are working on Typings

Before doing the full typings file, a simple typings file with this as the only contents, avoids the issue of working through every function (i.e. index.d.ts) 

```
declare var noTypeInfoYet: any; // any var name here really
export = noTypeInfoYet;
```

I was then able to get the Angular 2 library working in a Typescript app, using

`import * as Kinv from 'kinvey-angular2-sdk';`

And in the controller

```
this.db = Kinv.Kinvey;

      this.db.init({
        appKey: 'XXX',
        appSecret: 'YYY'
      });

      this.db.ping().then(function(response) {
        console.log('Kinvey Ping Success. Kinvey Service is alive, version: ' + response.version + ', response: ' + response.kinvey);
      }).catch(function(error) {
        console.log('Kinvey Ping Failed. Response: ' + error.message);
      });
```

Great if you are working on a full typings file, but I think this works in the meantime. (I think)
(Although I do have a problem still, but I think unrelated to typings]

**Comment by ThomasConner** [comment]
@alexbainbridge This is a big help to get started. I am new to Typescript and I am still learning a bit about how the typings interaction works. 

Here at Kinvey we always encourage that if you see a change that should be made then you should submit a pull request for us to review. I will continue to work on this as time permits. Thanks for your help.

**Comment by ThomasConner** [comment]
@alexbainbridge Can you take a look at `kinvey.d.ts` added with commit [a0ec5c4](https://github.com/Kinvey/angular2-sdk/commit/a0ec5c40a0411fa81d85808f0fe0b97c1e31c8f8) and see if this helps with typings?

**Comment by alexbainbridge** [comment]
Will do. Give me a few hours - but will be Tuesday (today)

Thanks @ThomasConner

**Comment by alexbainbridge** [comment]
I have not got this to work at all sadly. Its very frustrating

a) I previously DID get Kinvey Typescript Angular 2 working - but with some kind of JS error - so the UI was white screening. That was the version a couple of weeks back.  (no JS error logged)

b) Then I had a few days where the underlying dependencies were moved to 3.2 and this broke the Angular 2 fresh install completely because it was not updated at the same time.

c) Now with this version, getting assorted module errors on TypeScript. Not quite sure what they mean. 

Error: Cannot find module 'kinvey-angular2-sdk' from 

Spent a month on this on and off - can't afford much more actually. 

Have you got it working? On an Angular 2 Typescript app? Great to see how you did it!

**Comment by alexbainbridge** [comment]
I can do 2 more tests
a) JS version of the latest library, on my Angular 2 JS app (which is the test your instructions mention) ..... got that working before, but I have to do a few zone.js calls so the UI updates

That will test no regression generally

b) Completely fresh TypeScript app using typings - that I have never got working - but lets see if I do a fresh

However would be 10x easier if you have a demo angular 2 typescript app that you know works!

**Comment by ThomasConner** [comment]
@alexbainbridge Give me some time and I will try to get a typescript app working. I had one working using the Angular2 CLI at one time.

**Comment by alexbainbridge** [comment]
Hi Thomas - yeah I was using that - and its JS Angular 2 - which works :) (or did 2 weeks ago)

Thanks for any help!

**Comment by alexbainbridge** [comment]
HI Thomas

FYI Ionic 2 updated and now uses TypeScript 2 and beyond - which is a slightly different way of doing Typings. 

So now I am not clear if the problem is typescript or something with Rollup (ahead of time compilation of typescript) ...... certainly a problem though! 

I have opened a forum discussion with Ionic community to see if they can dig into what the problem could be
https://forum.ionicframework.com/t/kinvey-backend-rc0-typings-or-rollup-issue-help/65573

And forked an Ionic 2 Angular 2 Typescript app that I know works, with my adjustments, which I will use as a base until its right
https://github.com/alexbainbridge/ionic-conference-app

Incidentally, dont suppose you have any test Kinvey API keys that I can use for putting in a public repo - when people are debugging? 

Thanks! 
Alex

**Comment by ThomasConner** [comment]
@alexbainbridge You can signup for an account at https://console.kinvey.com if you haven't already and create a test/debug app to use.

**Comment by alexbainbridge** [comment]
Hi @ThomasConner I have a live Kinvey (prototype) app in Angular 1 (and the old Angular library)

Just dont want to put those keys up

At this time, the library is failing before getting to a connection, so for publicly showing my code, I dont need a test key.... will add one though!

**Comment by alexbainbridge** [comment]
Hi @ThomasConner 

I have kind of given up on this angle - here is my current thought! 

a) Typings looks good 
b) Now my problem is that you use webpack - and e.g. Ionic 2 (which is the largest UI framework on top of Angular 2) - uses Rollup. 

So then I found you have a pre-bundled version! Yay ;)

e.g.
https://download.kinvey.com/js/kinvey-html5-sdk-3.2.1.min.js

I have now moved to using the pre-bundled html5 SDK - but this means that the UI does not update when Kinvey data is returned..... so I have to wrap in zone.run - which is a bit boring - but at least is no longer a blocker to progressing development..... 

(Pretty sure your Angular 2 library handles UI updates directly)

SO QUESTION

Any chance of a pre-bundled angular 2 library?

Found this
https://download.kinvey.com/js/kinvey-angular2-sdk-3.1.0.min.js
but your latest adjustments, I think are not there yet (no 3.2 for example)

Either way, that version of the Angular 2 SDK isn't working) 

Error
referenceerror module is not defined


Summary
- I think you do need to spend some more time working out how to get Angular 2 SDK working via NPM etc.....  something isnt quite right
- Would be great if you could do a pre-bundled Angular 2 library that works (maybe the latest version, not yet in NPM, will be the fix actually) 
- Yay for HTML5 library!

Thanks!
Alex

**Comment by ThomasConner** [comment]
Hi @alexbainbridge

Thanks for the update. I am glad you have been able to get the HTML5 library working. I will look into making a pre-bundled version of the Angular2 library while also trying to fix the errors you reported.

**Comment by alexbainbridge** [comment]
Thanks @ThomasConner 

Would be great to have a pre-bundled Angular 2 on your CDN also - rather than just download subdomain on Kinvey....!
(I tried a few URLs, couldn't see it there)

**Comment by alexbainbridge** [comment]
Hi @ThomasConner 

Any luck?

Currently getting "Super expression must either be null or a function, not undefined" when using this library.....  so still not got it working

Developing on HTML5 library but really want to use the Angular 2 library if I can!

**Comment by thediycoder** [comment]
@alexbainbridge None yet.

**Comment by alexbainbridge** [comment]
Hi @thomasconner I am using the HTML5 library at the moment, which is why you haven't heard from me. Its possible to make that work, although the Angular 2 way would be more elegant (requires less code, as the HTML 5 library doesn't update the UI automatically)

Incidentally Typescript 2.1 which was just released enables untyped script to be imported to TypeScript apps.......  so hopefully in the new year, that will address the underlying concern!

Thanks!  Shout if I can help at all!

**Comment by Kayleith** [comment]
@alexbainbridge if I can ask, how in the world did you get the html5 library to work?

**Comment by alexbainbridge** [comment]
Hi Kay
What kind of app are you building? (what framework etc)
I just imported the javascript in my first file (for me, index.html), ahead of importing anything to do with Angular. 
That works, the pain I am finding is having to remember to apply Zone.run when I want the UI to update......

**Comment by Kayleith** [comment]
Well first I was doing react native. Found out that was a bust. Transferred most of the app to ionic 1 which was fine. then tried ionic 2. I was going go back ionic 1 as I have a deadline but if you figured out a way to make it work in ionic 2 that would be amazing

**Comment by alexbainbridge** [comment]
Hi Brian
Worked it out yet?

1) Add this to your index.html file (before pollyfill / main.js)

```
<script src="https://da189i1jfloii.cloudfront.net/js/kinvey-html5-sdk-3.3.3.min.js"></script>
```

Of course, you could/should download and call from a local location, if building an app rather than a web service....  If so, grab from here http://devcenter.kinvey.com/html5/downloads

2) Add this to your declarations.d.ts

```
declare const Kinvey: any;
```

3) Access Kinvey directly

e.g.
```
let activeUser = Kinvey.User.getActiveUser();
```

4) If you are having difficulties with the UI not updating (!) (which you are likely to run into as an issue) then do this:  Just bits to give you an idea...

Import NgZone
```
import { Component, NgZone } from '@angular/core';
```

Add to your constructor
```
constructor(public zone: NgZone) 
```

Wrap your Kinvey code with
```
zone.run(() => { CODE HERE });
```

Incidentally step 4 is the step I am expecting to be able to remove when I have got Angular 2 library working directly, rather than the HTML5 library......  I will next give that a go when I have updated to Typescript 2.1 - which handles untyped JS differently to current.

**Comment by alexbainbridge** [comment]
NPM version of the above works great. No need to directly include the file as above...... 

Also declarations file no longer needed....

**Comment by thomasconner** [comment]
@alexbainbridge We have added a declarations file. https://github.com/Kinvey/angular2-sdk/blob/master/src/kinvey.d.ts.

**Comment by thomasconner** [comment]
@Kayleith See above comment as well.

I have tested using the angular2 quickstart app and have been able to get things working. Please see https://github.com/KinveyApps/Angular2-Starter.

I have not tested with Ionic2 but I will be doing this shortly.

**Comment by alexbainbridge** [comment]
Thanks @thomasconner 

Key thing re your tests is whether it works on Typescript (as that was what the problem was before with Ionic 2) (The angular 2 starter when I last tried it was JS and I got that to work previously) 

Typescript looks like thats what you have addressed, which is wonderful, but just pointing out that this is what the difference is between the starter and Ionic 2 !

**Comment by thomasconner** [comment]
@alexbainbridge Thanks. I will give Ionic2 a try very soon and most likely will post a starter app for it as well.

**Comment by thomasconner** [comment]
@alexbainbridge Please see https://github.com/KinveyApps/Ionic2-Starter for getting started with Ionic2!

**Comment by alexbainbridge** [comment]
Thanks Thomas. 

I took a quick peek and looks great - currently sticking on the HTML5 Kinvey library for the instant as that has tested great! BUT when get a moment will come back and give this a try. Thanks for making it happen
