### ISSUE TITLE
Using angular2-sdk with webpack

### ISSUE THREAD

**Issue by R0muald** [Kinvey/angular2-sdk#5]
#### Steps to Reproduce

Set up angular2-starter with webpack and import the lib with `import { Kinvey } from 'kinvey-angular2-sdk'`.

#### Expected Result

Once login (executing `Kinvey.User.login()`), the app works correctly

#### Actual Result

When importing kinvey with `import { Kinvey } from 'kinvey-angular2-sdk'`, Once the app login, we can see that the javascript is not responding anymore (events issue) but there is no error part of the logs/console.
The issue also happens when using logout function.

The only way to get the app working is actually to point to the kinvey lib itself with:
```
import { Kinvey } from 'kinvey-angular2-sdk/dist/kinvey-angular2-sdk.js'
```

#### Sample Code that demonstrates the issue

looking at `kinvey-angular2-sdk@3.4.4` package.json :
```
{
 ...
  "main": "dist/kinvey-angular2-sdk.js",
  "module": "./src/kinvey.js",
}
```

It looks like webpack uses the `module` endpoint instead of the `main` endpoint. 
Even if that would work by removing the `module` endpoint, I'm not sure why when using `./src/kinvey.js`, the app does not work properly ...

#### Version of Kinvey HTML5 SDK

kinvey-html5-sdk@3.4.4

#### NodeJS version

node: 6.10.2
npm: 3.10.10

**Comment by thomasconner** [comment]
@R0muald Thanks for pointing this out. It is on our radar to take a look at as soon as we get some time.

**Comment by Mika571** [comment]
I'm struggling with this at the moment using the Angular CLI however changing all my import statements from
 `import { Kinvey } from 'kinvey-angular2-sdk'` 
to
 `import { Kinvey } from 'kinvey-angular2-sdk/dist/kinvey-angular2-sdk.js'`
 does not resolve the issue. Any hints?

**Comment by thomasconner** [comment]
@Mika571 Try replacing
```javascript
import { Kinvey } from 'kinvey-angular2-sdk';
```
with 
```javascript
const Kinvey = require('kinvey-angular2-sdk');
```

We will be supporting ES6 import in the future.

**Comment by Mika571** [comment]
No dice unfortunately using  `const Kinvey = require('kinvey-angular2-sdk');` gave the error `Cannot find name 'require'` so I installed `@types/node` and added the following to my tsconfig.app.json file
```
"types": [ "node" ],
"typeRoots": [ "../node_modules/@types" ]
```
But I now get `Cannot find namespace 'Kinvey'.` wherever I reference the Kinvey namespace.

**Comment by thomasconner** [comment]
I created the example app with the steps outlined at https://cli.angular.io. My `main.ts` file looks like 

```javascript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { Kinvey } from 'kinvey-angular2-sdk';

if (environment.production) {
  enableProdMode();
}

Kinvey.initialize({
  appKey: 'kid_rJQ3fa0il',
  appSecret: 'f934cde41bef41368bfa778692e690aa'
})
  .then(() => {
    const activeUser = Kinvey.User.getActiveUser();

    if (activeUser) {
      return activeUser.logout();
    }

    return null;
  })
  .then(() => {
    return Kinvey.User.login('admin', 'admin');
  })
  .then(() => {
    platformBrowserDynamic().bootstrapModule(AppModule);
  });
```

This works fine for me and loads the app. Can you share some code to show me what I am missing and that is causing the issue?

**Comment by Mika571** [comment]
I created a clone of the kinvey starter app here using the angular cli that shows the issue 
https://support.kinvey.com/support/discussions/topics/12000014786

**Comment by Mika571** [comment]
@thomasconner were you able to recreate this issue?

**Comment by Mika571** [comment]
@thomasconner  what platform versions are you using? I have tried creating a new blank project with angular cli version 1.3.2, node 6.11.2 and npm 4.6.1. When I modify my main ts the same as yours I get the following output:

`ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'kinvey-angular2-sdk' in 'D:\Users\User\Documents\CMI\angular\slyk\src'
resolve 'kinvey-angular2-sdk' in 'D:\Users\User\Documents\CMI\angular\slyk\src'
  Parsed request is a module
  using description file: D:\Users\User\Documents\CMI\angular\slyk\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Users\User\Documents\CMI\angular\slyk\package.json (relative path: ./src)
    resolve as module
      D:\Users\User\Documents\CMI\angular\slyk\src\node_modules doesn't exist or is not a directory
      D:\Users\User\Documents\CMI\angular\node_modules doesn't exist or is not a directory
      D:\Users\User\Documents\CMI\node_modules doesn't exist or is not a directory
      D:\Users\User\Documents\node_modules doesn't exist or is not a directory
      D:\Users\User\node_modules doesn't exist or is not a directory
      D:\Users\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\Users\User\Documents\CMI\angular\slyk\node_modules
        using description file: D:\Users\User\Documents\CMI\angular\slyk\package.json (relative path: ./node_modules)          Field 'browser' doesn't contain a valid alias configuration`

**Comment by Mika571** [comment]
I have tried this on 2 windows 10 machines as well as a mac with the same result.

**Comment by sittingbool** [comment]
There is no dist-folder after I install the sdk. The package json's main key says there should be. I guess thats why it can't be found.

**Comment by sittingbool** [comment]
I got it running with the following hotfix: 
1. Use the https://download.kinvey.com/js/kinvey-angular2-sdk-3.5.0.min.js and save it in node_modules/kinvey-angular2-sdk/dist (you have to create the dist folder).
2. dont use Kinvey.init like shown in the documenattion but rather use Kinvey.initialize (which hopefully does the same thing)

**Comment by Mika571** [comment]
The latest version seems to fix the webpack issues but I have updated my project to 3.9.0 but get the following compile errors relating to the SDK:
````
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (250,39): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (271,37): ',' expected.

ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (282,36): ',' expected.

ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (306,32): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (307,36): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (308,36): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (310,34): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (313,34): ',' expected.
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (245,9): Generic type 'CacheStore<T, Entity>' requires 2 ty
pe argument(s).
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (271,55): Generic type 'NetworkStore<T, Entity>' requires 2
 type argument(s).
ERROR in c:/my_project/node_modules/kinvey-angular2-sdk/kinvey-angular2-sdk.d.ts (282,54): Type 'typeof CacheStore' is not a constructor fun
ction type.
```

**Comment by Mika571** [comment]
I have updated to the latest version (3.9.0) but am still experiencing the issue with javascript not responding anymore (events issue) but there is no error part of the logs/console.

**Comment by thomasconner** [comment]
Ok I will take a look again. Thanks.

**Comment by thomasconner** [comment]
I am testing the app in Safari 11 but don't see an issue. I created a user, uploaded a file, download that same file using the link, and created a book using the datastore. Can you tell me what you do to see the issue?

Also with the release of 3.9.0 you can and should use `Kinvey.init()`. Reminder that this does not return a promise. The code would look like this:

```javascript
const config: Kinvey.ClientConfig = {
  appKey: '<appKey>',
  appSecret: '<appSecret>'
};

Kinvey.init(config);
enableProdMode();
platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by Mika571** [comment]
Thanks @thomasconner I really appreciate your help on this. 
I have changed `Kinvey.initialize` to `Kinvey.init` and am still seeing the issue issue on Chrome Version 61.0.3163.100 and Internet Explorer version 11 (after adding in polyfills). 
Starting the app on the login page and inspecting using the Augury plugin you can see that the appropriate component has loaded.
![image](https://user-images.githubusercontent.com/4703888/30834875-817eddc6-a298-11e7-8b98-f868b037fe3e.png)
After logging in however you see that none of the components load (navbar etc.) and trying to navigate to the other pages such as logout or files does not work.
![image](https://user-images.githubusercontent.com/4703888/30834915-b5db4e56-a298-11e7-9ed9-407fcdc445a8.png)
This is only resolved If I then refresh the page, which then shows the correctly loaded components.
![image](https://user-images.githubusercontent.com/4703888/30834999-23a0caf6-a299-11e7-8f1e-1c2647382e3b.png)

**Comment by Mika571** [comment]
@sittingbool unfortunately I still did not have any luck with your workaround. What version of npm angular cli etc. are you using?

**Comment by sittingbool** [comment]
Hi, I am not using angular cli, but Webpack from an example from AngularClass. but it shouldn't make any difference because both use node_modules. Can you show me the folder structure of the Kinvey node_module in your project? I had it wrong at first too. For example I forgot to change the name of the downloaded file. Maybe I see something. Also did you change from Kinvey.init to initialize?

**Comment by Mika571** [comment]
@thomasconner have you been able to replicate this issue?

**Comment by Mika571** [comment]
@sittingbool as you suggested I downloaded the `[minified 3.5 version](https://download.kinvey.com/js/kinvey-angular2-sdk-3.5.0.min.js)` and placed it under the node modules folder as
![image](https://user-images.githubusercontent.com/4703888/31278534-9df24d64-aae8-11e7-86e3-1a0cee042893.png)
The kinvey root folder has the following in it 
![image](https://user-images.githubusercontent.com/4703888/31278564-bad5fd86-aae8-11e7-82a6-4de91190a204.png)
Unfortunately I am still seeing the same problem,

**Comment by sittingbool** [comment]
@Mika571 Nope, you need to save it as "kinvey-angular2-sdk.min.js" which none of them is  and then place it into the dist folder ;).

**Comment by thomasconner** [comment]
@Mika571 I haven't had time to spend on this issue. I have been busy adding features to other JavaScript SDKs we release. I will try to spend some time with this soon. I think the issue might be with the Angular2 app and has nothing to do with the SDK but we shall see.

**Comment by Mika571** [comment]
@thomasconner I really need some assistance with this. The attached code is exactly the same as the sample app and yet I experience the issue above. If you are unavailable to assist is there anyone else who can?
[angular-cli.zip](https://github.com/Kinvey/angular2-sdk/files/1398048/angular-cli.zip)

**Comment by thomasconner** [comment]
@Mika571 I will try to take a look at it this weekend

**Comment by Mika571** [comment]
Thanks mate, I appreciate it.

**Comment by AntonDobrev** [comment]
I believe the latest issue with the navigation is rooted in the Angular router and the specifics between versions. More details here -  https://support.kinvey.com/discussions/topics/12000014786/page/2

**Comment by thomasconner** [comment]
@Mika571 does this resolve your issue?

**Comment by Mika571** [comment]
@thomasconner it does, thanks for all your assistance. It's greatly appreciated.
